-- FACTORY_CORE: Asset Hierarchy & Reference Entities
-- Follows ontology.md: Plant -> ProductionLine -> Machine -> Component -> Sensor

CREATE TABLE IF NOT EXISTS FACTORY_CORE.PLANT (
    plant_id VARCHAR(64) PRIMARY KEY,
    plant_code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(256) NOT NULL,
    location VARCHAR(256) NOT NULL,
    timezone VARCHAR(64) DEFAULT 'UTC',
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_CORE.PRODUCTION_LINE (
    line_id VARCHAR(64) PRIMARY KEY,
    plant_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.PLANT(plant_id),
    line_code VARCHAR(32) NOT NULL,
    name VARCHAR(256) NOT NULL,
    target_units_per_hour FLOAT DEFAULT 100.0,
    status VARCHAR(32) DEFAULT 'ACTIVE',
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_CORE.MACHINE (
    machine_id VARCHAR(64) PRIMARY KEY,
    line_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.PRODUCTION_LINE(line_id),
    machine_code VARCHAR(32) NOT NULL,
    name VARCHAR(256) NOT NULL,
    asset_type VARCHAR(64) DEFAULT 'MOTOR',
    criticality VARCHAR(32) DEFAULT 'HIGH', -- LOW, MEDIUM, HIGH, CRITICAL
    health_status VARCHAR(32) DEFAULT 'HEALTHY', -- HEALTHY, DEGRADING, CRITICAL, UNKNOWN
    state VARCHAR(32) DEFAULT 'RUNNING', -- RUNNING, IDLE, STOPPED, FAULTED, MAINTENANCE
    manufacturer VARCHAR(128),
    model VARCHAR(128),
    serial_number VARCHAR(128),
    commission_date DATE,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_CORE.COMPONENT (
    component_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    name VARCHAR(256) NOT NULL,
    component_type VARCHAR(64) NOT NULL, -- BEARING, STATOR, ROTOR, SHAFT, COUPLING, GEARBOX
    criticality VARCHAR(32) DEFAULT 'HIGH',
    installed_at TIMESTAMP_NTZ,
    health_status VARCHAR(32) DEFAULT 'HEALTHY'
);

CREATE TABLE IF NOT EXISTS FACTORY_CORE.SENSOR (
    sensor_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    sensor_type VARCHAR(64) NOT NULL, -- VIBRATION, TEMPERATURE, RPM, CURRENT, PRESSURE
    name VARCHAR(256) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    sampling_rate_hz FLOAT DEFAULT 1.0,
    range_min FLOAT NOT NULL,
    range_max FLOAT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);
