-- FACTORY_PRODUCTION & FACTORY_MAINTENANCE Tables

CREATE TABLE IF NOT EXISTS FACTORY_PRODUCTION.PRODUCTION_RUN (
    run_id VARCHAR(64) PRIMARY KEY,
    line_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.PRODUCTION_LINE(line_id),
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    product_code VARCHAR(64) NOT NULL,
    start_time TIMESTAMP_NTZ NOT NULL,
    end_time TIMESTAMP_NTZ,
    planned_units INT NOT NULL,
    actual_units INT NOT NULL,
    good_units INT NOT NULL,
    scrap_units INT NOT NULL,
    ideal_cycle_time_seconds FLOAT DEFAULT 3.6,
    status VARCHAR(32) DEFAULT 'COMPLETED'
);

CREATE TABLE IF NOT EXISTS FACTORY_PRODUCTION.DOWNTIME_EVENT (
    downtime_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    line_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.PRODUCTION_LINE(line_id),
    start_time TIMESTAMP_NTZ NOT NULL,
    end_time TIMESTAMP_NTZ,
    duration_minutes FLOAT NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    category VARCHAR(32) DEFAULT 'UNPLANNED',
    description VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS FACTORY_MAINTENANCE.MAINTENANCE_EVENT (
    maintenance_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    maintenance_type VARCHAR(64) NOT NULL, -- INSPECTION, REPLACEMENT, LUBRICATION, REPAIR
    performed_at TIMESTAMP_NTZ NOT NULL,
    technician_name VARCHAR(128) NOT NULL,
    duration_hours FLOAT NOT NULL,
    notes VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS FACTORY_MAINTENANCE.WORK_ORDER (
    work_order_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    investigation_id VARCHAR(64),
    recommendation_id VARCHAR(64),
    title VARCHAR(256) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    failure_mode VARCHAR(64) NOT NULL,
    priority VARCHAR(32) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    status VARCHAR(32) DEFAULT 'DRAFT', -- DRAFT, PENDING_APPROVAL, APPROVED, SCHEDULED, IN_PROGRESS, COMPLETED, CANCELLED
    assigned_to VARCHAR(128),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    scheduled_date TIMESTAMP_NTZ,
    completed_at TIMESTAMP_NTZ,
    idempotency_key VARCHAR(128) UNIQUE
);
