-- FACTORY_RELIABILITY & FACTORY_INTELLIGENCE Tables

CREATE TABLE IF NOT EXISTS FACTORY_RELIABILITY.FAILURE (
    failure_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    failure_mode VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP_NTZ NOT NULL,
    root_cause VARCHAR(1024) NOT NULL,
    downtime_hours FLOAT NOT NULL,
    maintenance_action_taken VARCHAR(1024),
    resolved_at TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS FACTORY_RELIABILITY.FAILURE_RISK (
    risk_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    failure_mode VARCHAR(64) NOT NULL,
    risk_score FLOAT NOT NULL,
    prediction_horizon_hours INT DEFAULT 72,
    model_version VARCHAR(64) DEFAULT 'v1.2.0-bearing-xgb',
    prediction_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    confidence FLOAT DEFAULT 0.85
);

CREATE TABLE IF NOT EXISTS FACTORY_RELIABILITY.HEALTH_ASSESSMENT (
    assessment_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    health_status VARCHAR(32) NOT NULL,
    health_score FLOAT NOT NULL,
    primary_concern VARCHAR(256),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.ALERT (
    alert_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    severity VARCHAR(32) NOT NULL, -- LOW, MEDIUM, HIGH, CRITICAL
    status VARCHAR(32) DEFAULT 'OPEN', -- OPEN, INVESTIGATING, ACTION_PROPOSED, RESOLVED, DISMISSED
    trigger_reason VARCHAR(512) NOT NULL,
    risk_score FLOAT NOT NULL,
    failure_mode VARCHAR(64) DEFAULT 'BEARING_DEGRADATION',
    dedup_key VARCHAR(128),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    acknowledged_at TIMESTAMP_NTZ,
    resolved_at TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.INVESTIGATION (
    investigation_id VARCHAR(64) PRIMARY KEY,
    alert_id VARCHAR(64) REFERENCES FACTORY_INTELLIGENCE.ALERT(alert_id),
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    status VARCHAR(32) DEFAULT 'CREATED', -- CREATED, IN_PROGRESS, WAITING_FOR_APPROVAL, COMPLETED, CLOSED
    failure_mode VARCHAR(64) NOT NULL,
    confidence FLOAT DEFAULT 0.0,
    summary VARCHAR(2048),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.EVIDENCE (
    evidence_id VARCHAR(64) PRIMARY KEY,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    evidence_type VARCHAR(64) NOT NULL, -- TELEMETRY, MAINTENANCE, FAILURE_HISTORY, DOCUMENT, PRODUCTION
    source VARCHAR(128) NOT NULL,
    metric VARCHAR(64) NOT NULL,
    observed_value VARCHAR(256) NOT NULL,
    baseline_value VARCHAR(256),
    relationship VARCHAR(32) DEFAULT 'SUPPORTS', -- SUPPORTS, CONTRADICTS, CORRELATES
    summary VARCHAR(1024) NOT NULL,
    timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.HYPOTHESIS (
    hypothesis_id VARCHAR(64) PRIMARY KEY,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    hypothesis_name VARCHAR(256) NOT NULL,
    failure_mode VARCHAR(64) NOT NULL,
    confidence FLOAT NOT NULL,
    status VARCHAR(32) DEFAULT 'EVALUATED',
    rationale VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.FINDING (
    finding_id VARCHAR(64) PRIMARY KEY,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    summary VARCHAR(2048) NOT NULL,
    failure_mode VARCHAR(64) NOT NULL,
    confidence FLOAT NOT NULL,
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.RECOMMENDATION (
    recommendation_id VARCHAR(64) PRIMARY KEY,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    title VARCHAR(256) NOT NULL,
    action_description VARCHAR(2048) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    action_required BOOLEAN DEFAULT TRUE,
    estimated_downtime_hours FLOAT DEFAULT 2.0
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.ML_PREDICTION (
    prediction_id VARCHAR(64) PRIMARY KEY,
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    component_id VARCHAR(64) REFERENCES FACTORY_CORE.COMPONENT(component_id),
    failure_mode VARCHAR(64) NOT NULL,
    failure_probability FLOAT NOT NULL,
    prediction_horizon_hours INT DEFAULT 24,
    model_name VARCHAR(128) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    training_dataset_version VARCHAR(64) DEFAULT 'v2026.03',
    feature_schema_version VARCHAR(64) DEFAULT 'v1.0',
    confidence FLOAT DEFAULT 0.88,
    threshold_exceeded BOOLEAN DEFAULT FALSE,
    top_contributing_features VARCHAR(2048),
    feature_timestamp TIMESTAMP_NTZ NOT NULL,
    prediction_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_INTELLIGENCE.PREDICTION_OUTCOME (
    outcome_id VARCHAR(64) PRIMARY KEY,
    prediction_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.ML_PREDICTION(prediction_id),
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    predicted_failure BOOLEAN NOT NULL,
    actual_failure BOOLEAN NOT NULL,
    prediction_horizon_hours INT DEFAULT 24,
    lead_time_hours FLOAT,
    verification_id VARCHAR(64),
    evaluated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    is_correct BOOLEAN NOT NULL,
    notes VARCHAR(1024)
);
