-- FACTORY_AGENT, FACTORY_AUDIT, and FACTORY_KNOWLEDGE Tables

CREATE TABLE IF NOT EXISTS FACTORY_AGENT.APPROVAL (
    approval_id VARCHAR(64) PRIMARY KEY,
    action_id VARCHAR(64) NOT NULL,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    status VARCHAR(32) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, ESCALATED
    requested_by VARCHAR(128) DEFAULT 'ReliabilityAgent',
    reviewed_by VARCHAR(128),
    reviewed_at TIMESTAMP_NTZ,
    decision_reason VARCHAR(1024),
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_AGENT.VERIFICATION (
    verification_id VARCHAR(64) PRIMARY KEY,
    investigation_id VARCHAR(64) NOT NULL REFERENCES FACTORY_INTELLIGENCE.INVESTIGATION(investigation_id),
    work_order_id VARCHAR(64) NOT NULL REFERENCES FACTORY_MAINTENANCE.WORK_ORDER(work_order_id),
    machine_id VARCHAR(64) NOT NULL REFERENCES FACTORY_CORE.MACHINE(machine_id),
    verified_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    pre_vibration_rms FLOAT NOT NULL,
    post_vibration_rms FLOAT NOT NULL,
    pre_temperature_c FLOAT NOT NULL,
    post_temperature_c FLOAT NOT NULL,
    pre_risk_score FLOAT NOT NULL,
    post_risk_score FLOAT NOT NULL,
    is_recovered BOOLEAN NOT NULL,
    oee_recovery_pct FLOAT DEFAULT 0.0,
    notes VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS FACTORY_AGENT.AGENT_EXECUTION (
    execution_id VARCHAR(64) PRIMARY KEY,
    agent_name VARCHAR(128) NOT NULL,
    workflow_name VARCHAR(128) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    trigger_id VARCHAR(64),
    started_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    completed_at TIMESTAMP_NTZ,
    status VARCHAR(32) DEFAULT 'RUNNING',
    input_context VARIANT,
    output_summary VARCHAR(4096)
);

CREATE TABLE IF NOT EXISTS FACTORY_AGENT.TOOL_CALL (
    tool_call_id VARCHAR(64) PRIMARY KEY,
    execution_id VARCHAR(64) NOT NULL REFERENCES FACTORY_AGENT.AGENT_EXECUTION(execution_id),
    tool_name VARCHAR(128) NOT NULL,
    arguments VARIANT NOT NULL,
    result VARIANT,
    started_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    duration_ms FLOAT DEFAULT 0.0,
    is_success BOOLEAN DEFAULT TRUE,
    error_message VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS FACTORY_AUDIT.AUDIT_EVENT (
    audit_id VARCHAR(64) PRIMARY KEY,
    actor VARCHAR(128) NOT NULL,
    action_type VARCHAR(128) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    details VARIANT,
    status VARCHAR(32) DEFAULT 'SUCCESS'
);

CREATE TABLE IF NOT EXISTS FACTORY_KNOWLEDGE.DOCUMENT (
    document_id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    doc_type VARCHAR(64) NOT NULL,
    machine_model VARCHAR(128) NOT NULL,
    version VARCHAR(32) DEFAULT '1.0',
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACTORY_KNOWLEDGE.KNOWLEDGE_CHUNK (
    chunk_id VARCHAR(64) PRIMARY KEY,
    document_id VARCHAR(64) NOT NULL REFERENCES FACTORY_KNOWLEDGE.DOCUMENT(document_id),
    section_title VARCHAR(256) NOT NULL,
    content VARCHAR(8192) NOT NULL,
    tags ARRAY
);
