"""Canonical Ingestion Source-to-Target Manifest.

Defines the authoritative 19-dataset manifest mapping canonical CSV sources
to Snowflake RAW landing tables, CORE conformed tables, expected schemas,
cardinalities, primary keys, and file formats.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass(frozen=True)
class CanonicalEntityManifest:
    """Manifest definition for an individual canonical entity dataset."""

    entity_name: str
    source_filename: str
    raw_table: str
    core_table: str
    stage_path: str
    expected_columns: List[str]
    expected_rows: int
    primary_keys: List[str]
    file_format: str = "CSV_CANONICAL"
    is_high_volume: bool = False
    description: str = ""


CANONICAL_MANIFEST: Dict[str, CanonicalEntityManifest] = {
    "machine": CanonicalEntityManifest(
        entity_name="machine",
        source_filename="machine.csv",
        raw_table="COCO_FACTORY.RAW.MACHINE",
        core_table="COCO_FACTORY.CORE.MACHINE",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/machine.csv",
        expected_columns=[
            "machine_id",
            "machine_name",
            "machine_type",
            "model",
            "plant_id",
            "line_id",
            "purchase_date",
            "install_date",
            "expected_life_years",
            "expected_end_of_life_date",
            "criticality",
            "ideal_cycle_time_sec",
            "rated_power_kw",
            "shifts_per_day",
            "pm_interval_days",
        ],
        expected_rows=25,
        primary_keys=["machine_id"],
        description="Master asset dimension representing factory machines",
    ),
    "component": CanonicalEntityManifest(
        entity_name="component",
        source_filename="component.csv",
        raw_table="COCO_FACTORY.RAW.COMPONENT",
        core_table="COCO_FACTORY.CORE.COMPONENT",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/component.csv",
        expected_columns=[
            "component_id",
            "machine_id",
            "component_type",
            "model",
            "purchase_date",
            "install_date",
            "expected_life_hrs",
            "operating_hours_used",
            "projected_end_of_life_date",
        ],
        expected_rows=141,
        primary_keys=["component_id"],
        description="Machine components and subassemblies dimension",
    ),
    "sensor": CanonicalEntityManifest(
        entity_name="sensor",
        source_filename="sensor.csv",
        raw_table="COCO_FACTORY.RAW.SENSOR",
        core_table="COCO_FACTORY.CORE.SENSOR",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/sensor.csv",
        expected_columns=[
            "sensor_id",
            "machine_id",
            "component_id",
            "sensor_type",
            "unit",
            "sampling_rate_hz",
            "warn_threshold",
            "crit_threshold",
            "threshold_direction",
        ],
        expected_rows=144,
        primary_keys=["sensor_id"],
        description="Physical sensor metadata, measurement units and threshold configurations",
    ),
    "sensor_reading": CanonicalEntityManifest(
        entity_name="sensor_reading",
        source_filename="sensor_reading.csv",
        raw_table="COCO_FACTORY.RAW.SENSOR_READING",
        core_table="COCO_FACTORY.CORE.SENSOR_READING",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/sensor_reading.csv",
        expected_columns=[
            "sensor_id",
            "ts",
            "value",
        ],
        expected_rows=2903040,
        primary_keys=["sensor_id", "ts"],
        is_high_volume=True,
        description="High-frequency 1-minute IoT telemetry readings (2.9M+ rows)",
    ),
    "sensor_reading_hourly": CanonicalEntityManifest(
        entity_name="sensor_reading_hourly",
        source_filename="sensor_reading_hourly.csv",
        raw_table="COCO_FACTORY.RAW.SENSOR_READING_HOURLY",
        core_table="COCO_FACTORY.CORE.SENSOR_READING_HOURLY",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/sensor_reading_hourly.csv",
        expected_columns=[
            "sensor_id",
            "ts",
            "run_fraction",
            "avg_running",
            "min_running",
            "max_running",
        ],
        expected_rows=1254528,
        primary_keys=["sensor_id", "ts"],
        is_high_volume=True,
        description="Hourly pre-aggregated sensor telemetry and operational run fractions",
    ),
    "production_order": CanonicalEntityManifest(
        entity_name="production_order",
        source_filename="production_order.csv",
        raw_table="COCO_FACTORY.RAW.PRODUCTION_ORDER",
        core_table="COCO_FACTORY.CORE.PRODUCTION_ORDER",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/production_order.csv",
        expected_columns=[
            "production_order_id",
            "machine_id",
            "product_id",
            "customer",
            "planned_qty",
            "produced_qty",
            "planned_start",
            "planned_end",
            "due_date",
            "priority",
            "status",
        ],
        expected_rows=1524,
        primary_keys=["production_order_id"],
        description="Customer production orders with scheduling and delivery commitments",
    ),
    "production_run": CanonicalEntityManifest(
        entity_name="production_run",
        source_filename="production_run.csv",
        raw_table="COCO_FACTORY.RAW.PRODUCTION_RUN",
        core_table="COCO_FACTORY.CORE.PRODUCTION_RUN",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/production_run.csv",
        expected_columns=[
            "run_id",
            "machine_id",
            "product_id",
            "production_order_id",
            "shift_id",
            "shift_date",
            "start_ts",
            "end_ts",
            "planned_time_min",
            "planned_maintenance_min",
            "unplanned_downtime_min",
            "run_time_min",
            "ideal_cycle_time_sec",
            "total_count",
            "good_count",
            "reject_count",
        ],
        expected_rows=19593,
        primary_keys=["run_id"],
        description="Shift-level production run execution logs for OEE computation",
    ),
    "downtime_event": CanonicalEntityManifest(
        entity_name="downtime_event",
        source_filename="downtime_event.csv",
        raw_table="COCO_FACTORY.RAW.DOWNTIME_EVENT",
        core_table="COCO_FACTORY.CORE.DOWNTIME_EVENT",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/downtime_event.csv",
        expected_columns=[
            "event_id",
            "machine_id",
            "run_id",
            "reason_code",
            "category",
            "reason_description",
            "start_ts",
            "end_ts",
            "duration_min",
            "wo_id",
            "notes",
        ],
        expected_rows=67385,
        primary_keys=["event_id"],
        description="Detailed machine downtime records categorized into planned/unplanned downtime",
    ),
    "maintenance_work_order": CanonicalEntityManifest(
        entity_name="maintenance_work_order",
        source_filename="maintenance_work_order.csv",
        raw_table="COCO_FACTORY.RAW.MAINTENANCE_WORK_ORDER",
        core_table="COCO_FACTORY.CORE.MAINTENANCE_WORK_ORDER",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/maintenance_work_order.csv",
        expected_columns=[
            "wo_id",
            "machine_id",
            "component_id",
            "wo_type",
            "source",
            "priority",
            "failure_code",
            "status",
            "scheduled_date",
            "opened_ts",
            "started_ts",
            "closed_ts",
            "assigned_to",
            "technicians",
            "labor_hours",
            "parts_cost",
            "labor_cost",
            "cost",
            "prediction_id",
        ],
        expected_rows=637,
        primary_keys=["wo_id"],
        description="Maintenance work orders tracking remediation, labor, parts, and lifecycle",
    ),
    "technician": CanonicalEntityManifest(
        entity_name="technician",
        source_filename="technician.csv",
        raw_table="COCO_FACTORY.RAW.TECHNICIAN",
        core_table="COCO_FACTORY.CORE.TECHNICIAN",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/technician.csv",
        expected_columns=[
            "technician_id",
            "name",
            "skill_area",
            "shift",
            "hourly_rate_inr",
        ],
        expected_rows=6,
        primary_keys=["technician_id"],
        description="Maintenance technician roster with skill specialties and rates",
    ),
    "maintenance_log": CanonicalEntityManifest(
        entity_name="maintenance_log",
        source_filename="maintenance_log.csv",
        raw_table="COCO_FACTORY.RAW.MAINTENANCE_LOG",
        core_table="COCO_FACTORY.CORE.MAINTENANCE_LOG",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/maintenance_log.csv",
        expected_columns=[
            "log_id",
            "wo_id",
            "machine_id",
            "component_id",
            "technician_id",
            "log_ts",
            "wo_type",
            "failure_code",
            "root_cause_category",
            "fault_class",
            "symptom",
            "action_taken",
            "downtime_min",
            "early_warning_hours",
            "note_text",
        ],
        expected_rows=610,
        primary_keys=["log_id"],
        description="Detailed technician maintenance field logs, root cause, and symptoms",
    ),
    "wo_part_usage": CanonicalEntityManifest(
        entity_name="wo_part_usage",
        source_filename="wo_part_usage.csv",
        raw_table="COCO_FACTORY.RAW.WO_PART_USAGE",
        core_table="COCO_FACTORY.CORE.WO_PART_USAGE",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/wo_part_usage.csv",
        expected_columns=[
            "wo_id",
            "part_id",
            "qty",
            "unit_cost_inr",
            "line_cost_inr",
        ],
        expected_rows=671,
        primary_keys=["wo_id", "part_id"],
        description="Bill of materials line items consumed by maintenance work orders",
    ),
    "spare_part": CanonicalEntityManifest(
        entity_name="spare_part",
        source_filename="spare_part.csv",
        raw_table="COCO_FACTORY.RAW.SPARE_PART",
        core_table="COCO_FACTORY.CORE.SPARE_PART",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/spare_part.csv",
        expected_columns=[
            "part_id",
            "part_name",
            "part_category",
            "compatible_model",
            "unit_cost_inr",
            "supplier_id",
            "lead_time_days",
            "stock_qty",
            "reorder_level",
            "reorder_qty",
            "warehouse_bin",
        ],
        expected_rows=32,
        primary_keys=["part_id"],
        description="Spare parts inventory catalog, stock levels, reorder points, and bin locations",
    ),
    "supplier": CanonicalEntityManifest(
        entity_name="supplier",
        source_filename="supplier.csv",
        raw_table="COCO_FACTORY.RAW.SUPPLIER",
        core_table="COCO_FACTORY.CORE.SUPPLIER",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/supplier.csv",
        expected_columns=[
            "supplier_id",
            "supplier_name",
            "country",
            "avg_lead_time_days",
            "on_time_delivery_pct",
        ],
        expected_rows=12,
        primary_keys=["supplier_id"],
        description="Component and parts suppliers with lead times and delivery metrics",
    ),
    "purchase_order": CanonicalEntityManifest(
        entity_name="purchase_order",
        source_filename="purchase_order.csv",
        raw_table="COCO_FACTORY.RAW.PURCHASE_ORDER",
        core_table="COCO_FACTORY.CORE.PURCHASE_ORDER",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/purchase_order.csv",
        expected_columns=[
            "po_id",
            "supplier_id",
            "part_id",
            "qty",
            "unit_cost_inr",
            "order_date",
            "expected_delivery_date",
            "actual_delivery_date",
            "status",
            "order_type",
            "linked_wo_id",
        ],
        expected_rows=217,
        primary_keys=["po_id"],
        description="Procurement purchase orders placed to replenish spare parts",
    ),
    "product": CanonicalEntityManifest(
        entity_name="product",
        source_filename="product.csv",
        raw_table="COCO_FACTORY.RAW.PRODUCT",
        core_table="COCO_FACTORY.CORE.PRODUCT",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/product.csv",
        expected_columns=[
            "product_id",
            "product_name",
            "product_family",
            "unit_price_inr",
            "unit_margin_inr",
            "cycle_time_multiplier",
        ],
        expected_rows=8,
        primary_keys=["product_id"],
        description="Manufactured product catalog, unit economics, and standard cycle time multipliers",
    ),
    "alert": CanonicalEntityManifest(
        entity_name="alert",
        source_filename="alert.csv",
        raw_table="COCO_FACTORY.RAW.ALERT",
        core_table="COCO_FACTORY.CORE.ALERT",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/alert.csv",
        expected_columns=[
            "alert_id",
            "machine_id",
            "component_id",
            "sensor_id",
            "ts",
            "severity",
            "alert_type",
            "reading_value",
            "threshold_value",
            "message",
            "status",
            "priority_score",
            "recommended_action",
            "assigned_to",
            "production_order_id",
            "acknowledged_by",
            "acknowledged_ts",
            "closed_ts",
            "wo_id",
        ],
        expected_rows=1142,
        primary_keys=["alert_id"],
        description="Automated telemetry anomalies and condition monitoring threshold alert events",
    ),
    "prediction": CanonicalEntityManifest(
        entity_name="prediction",
        source_filename="prediction.csv",
        raw_table="COCO_FACTORY.RAW.PREDICTION",
        core_table="COCO_FACTORY.CORE.PREDICTION",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/prediction.csv",
        expected_columns=[
            "prediction_id",
            "scored_ts",
            "machine_id",
            "suspected_component_id",
            "model_name",
            "horizon_days",
            "failure_prob",
            "risk_level",
            "top_features",
        ],
        expected_rows=326,
        primary_keys=["prediction_id"],
        description="Predictive maintenance failure risk inference scores and feature attributions",
    ),
    "knowledge_doc": CanonicalEntityManifest(
        entity_name="knowledge_doc",
        source_filename="knowledge_doc.csv",
        raw_table="COCO_FACTORY.RAW.KNOWLEDGE_DOC",
        core_table="COCO_FACTORY.CORE.KNOWLEDGE_DOC",
        stage_path="@COCO_FACTORY.RAW.FACTORY_STAGE/knowledge_doc.csv",
        expected_columns=[
            "doc_id",
            "doc_type",
            "machine_type",
            "component_type",
            "title",
            "content",
        ],
        expected_rows=16,
        primary_keys=["doc_id"],
        description="Standard operating procedures, OEM manuals, and troubleshooting knowledge documents",
    ),
}


def get_manifest(entity_name: str) -> CanonicalEntityManifest:
    """Retrieve manifest entry for a canonical entity."""
    if entity_name not in CANONICAL_MANIFEST:
        raise KeyError(f"Unknown canonical entity: {entity_name}")
    return CANONICAL_MANIFEST[entity_name]


def list_all_manifests() -> List[CanonicalEntityManifest]:
    """Retrieve all 19 canonical entity manifest entries in canonical order."""
    return list(CANONICAL_MANIFEST.values())


def get_total_expected_rows() -> int:
    """Calculate total expected row count across all 19 canonical datasets."""
    return sum(m.expected_rows for m in CANONICAL_MANIFEST.values())
