"""Domain enumerations for Factory Reliability Command Center."""

from enum import Enum


class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADING = "DEGRADING"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"


class MachineState(str, Enum):
    RUNNING = "RUNNING"
    IDLE = "IDLE"
    STOPPED = "STOPPED"
    FAULTED = "FAULTED"
    MAINTENANCE = "MAINTENANCE"
    STARTING = "STARTING"
    STOPPING = "STOPPING"
    UNKNOWN = "UNKNOWN"


class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"



class AlertStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"


class InvestigationStatus(str, Enum):
    CREATED = "CREATED"
    TRIGGERED = "TRIGGERED"
    COLLECTING_EVIDENCE = "COLLECTING_EVIDENCE"
    ANALYZING = "ANALYZING"
    FINDING_READY = "FINDING_READY"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ACTIONED = "ACTIONED"
    VERIFIED = "VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    REQUIRES_FOLLOW_UP = "REQUIRES_FOLLOW_UP"
    CLOSED = "CLOSED"
    FAILED = "FAILED"
    # Backward compatibility
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"


class WorkOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    CANCELLED = "CANCELLED"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    FAILED = "FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    INCONCLUSIVE = "INCONCLUSIVE"
    PENDING = "PENDING"


class ActionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    VERIFIED = "VERIFIED"


class ActionProposalStatus(str, Enum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"


class FailureMode(str, Enum):
    NORMAL_OPERATION = "NORMAL_OPERATION"
    BEARING_DEGRADATION = "BEARING_DEGRADATION"
    MOTOR_OVERHEATING = "MOTOR_OVERHEATING"
    OVERHEATING = "OVERHEATING"
    MISALIGNMENT = "MISALIGNMENT"
    MECHANICAL_WEAR = "MECHANICAL_WEAR"
    LUBRICATION_FAILURE = "LUBRICATION_FAILURE"
    SENSOR_FAILURE = "SENSOR_FAILURE"
    UNPLANNED_DOWNTIME = "UNPLANNED_DOWNTIME"


class SensorType(str, Enum):
    VIBRATION = "VIBRATION"
    TEMPERATURE = "TEMPERATURE"
    RPM = "RPM"
    CURRENT = "CURRENT"
    PRESSURE = "PRESSURE"
    FLOW = "FLOW"


class ToolMode(str, Enum):
    READ = "READ"
    ACTION = "ACTION"


class TriggerType(str, Enum):
    PREDICTION = "PREDICTION"
    MACHINE = "MACHINE"
    ALERT = "ALERT"
    CRITICAL_ALERT = "CRITICAL_ALERT"
    PREDICTIVE_FAILURE = "PREDICTIVE_FAILURE"
    USER_QUERY = "USER_QUERY"
    EVENT = "EVENT"
    SCHEDULE = "SCHEDULE"
    USER = "USER"
    WORKFLOW = "WORKFLOW"
    EXTERNAL = "EXTERNAL"



class AgentStatus(str, Enum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    WAITING_FOR_TOOL = "WAITING_FOR_TOOL"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
